<?php
if(!defined('ABSPATH'))exit;define('NBU_T_VER','1.15.2');
function nbu_t_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');}add_action('after_setup_theme','nbu_t_setup');
function nbu_t_assets(){wp_enqueue_style('nbu-terminal',get_stylesheet_uri(),array(),NBU_T_VER);wp_enqueue_script('nbu-terminal',get_template_directory_uri().'/assets/js/app.js',array(),NBU_T_VER,true);wp_enqueue_script('nbu-terminal-crt',get_template_directory_uri().'/assets/js/crt-companion.js',array(),NBU_T_VER,true);}add_action('wp_enqueue_scripts','nbu_t_assets');
function nbu_t_login_style(){wp_enqueue_style('nbu-terminal-login',get_template_directory_uri().'/assets/css/login.css',array(),NBU_T_VER);}add_action('login_enqueue_scripts','nbu_t_login_style');
function nbu_t_login_brand($url){return home_url('/');}add_filter('login_headerurl','nbu_t_login_brand');
function nbu_t_login_title($title){return get_bloginfo('name').' — Sign in';}add_filter('login_headertext','nbu_t_login_title');
function nbu_t_customize($c){$c->add_section('nbu_t',array('title'=>'Newbeultra Appearance','priority'=>30));$c->add_setting('nbu_t_palette',array('default'=>'termius','sanitize_callback'=>'sanitize_key'));$c->add_control('nbu_t_palette',array('section'=>'nbu_t','label'=>'Default Color Palette','description'=>'Site-wide setting. Visitors cannot change this.','type'=>'select','choices'=>array('termius'=>'Termius Dark','nord'=>'Nord Dark','dracula'=>'Dracula','monokai'=>'Monokai','hackerblue'=>'Hacker Blue','hackergreen'=>'Hacker Green','flexoki'=>'Flexoki Dark','light'=>'Light Workspace')));$c->add_setting('nbu_t_radius',array('default'=>'16','sanitize_callback'=>'absint'));$c->add_control('nbu_t_radius',array('section'=>'nbu_t','label'=>'Panel Radius','type'=>'select','choices'=>array('10'=>'10px','14'=>'14px','16'=>'16px','20'=>'20px')));$c->add_setting('nbu_t_density',array('default'=>'comfortable','sanitize_callback'=>'sanitize_key'));$c->add_control('nbu_t_density',array('section'=>'nbu_t','label'=>'UI Density','type'=>'select','choices'=>array('compact'=>'Compact','comfortable'=>'Comfortable','spacious'=>'Spacious')));
$c->add_section('nbu_t_crt',array('title'=>'CRT Companion','priority'=>31));
$c->add_setting('nbu_t_crt_color',array('default'=>'#00ff41','sanitize_callback'=>'sanitize_hex_color'));$c->add_control(new WP_Customize_Color_Control($c,'nbu_t_crt_color',array('section'=>'nbu_t_crt','label'=>'Display Color')));
$c->add_setting('nbu_t_crt_scanlines',array('default'=>'medium','sanitize_callback'=>'sanitize_key'));$c->add_control('nbu_t_crt_scanlines',array('section'=>'nbu_t_crt','label'=>'Scanline Density','type'=>'select','choices'=>array('off'=>'Off','fine'=>'Fine','medium'=>'Medium','heavy'=>'Heavy')));
$c->add_setting('nbu_t_crt_glow',array('default'=>'medium','sanitize_callback'=>'sanitize_key'));$c->add_control('nbu_t_crt_glow',array('section'=>'nbu_t_crt','label'=>'Glow Intensity','type'=>'select','choices'=>array('low'=>'Low','medium'=>'Medium','high'=>'High')));
}add_action('customize_register','nbu_t_customize');
function nbu_t_vars(){ $ps=array('termius'=>array('#171924','#1d2033','#282b3d','#30344b','#ddddea','#a9abbb','#777b92','#7c83ff','#51d6a7','#f5c76e'),'nord'=>array('#2e3440','#292e39','#3b4252','#434c5e','#eceff4','#d8dee9','#81a1c1','#88c0d0','#a3be8c','#ebcb8b'),'dracula'=>array('#282a36','#21222c','#343746','#414558','#f8f8f2','#d9d5ef','#8b89a6','#bd93f9','#50fa7b','#f1fa8c'),'monokai'=>array('#272822','#20211d','#35362f','#414339','#f8f8f2','#d5d6c8','#8e9283','#a6e22e','#a6e22e','#e6db74'),'hackerblue'=>array('#071824','#0a2131','#0d2b3e','#12354b','#d8f1ff','#a9c9db','#668da2','#32a7ff','#2fe0a1','#f4cd70'),'hackergreen'=>array('#07130d','#0b1b12','#102519','#163322','#d8f7df','#a5ccb0','#5f8e6c','#4eea83','#4eea83','#e6d75d'),'flexoki'=>array('#1c1b1a','#242321','#302e2b','#3a3835','#cecdc3','#b7b5ac','#87847b','#d0a215','#879a39','#d0a215'),'light'=>array('#f4f5f8','#ffffff','#ffffff','#edf0f7','#20222a','#515767','#7a8090','#5765d9','#248b64','#a96b13'));$v=$ps[get_theme_mod('nbu_t_palette','termius')]??$ps['termius'];$n=array('--bg','--side','--panel','--raise','--text','--sub','--muted','--accent','--ok','--warn');$x=':root{';foreach($n as $i=>$k)$x.=$k.':'.$v[$i].';';$x.='--radius:'.absint(get_theme_mod('nbu_t_radius',16)).'px;';$d=get_theme_mod('nbu_t_density','comfortable');$x.='--density:'.($d==='compact'?'.84':($d==='spacious'?'1.18':'1')).';';
$x.='--crt-color:'.sanitize_hex_color(get_theme_mod('nbu_t_crt_color','#00ff41')).';';
$scan=get_theme_mod('nbu_t_crt_scanlines','medium');$scanMap=array('off'=>array('1px','0%'),'fine'=>array('2px','22%'),'medium'=>array('2px','35%'),'heavy'=>array('3px','52%'));$sv=$scanMap[$scan]??$scanMap['medium'];$x.='--crt-scan-gap:'.$sv[0].';--crt-scan-alpha:'.$sv[1].';';
$glow=get_theme_mod('nbu_t_crt_glow','medium');$glowMap=array('low'=>'.6','medium'=>'1','high'=>'1.6');$x.='--crt-glow-mult:'.($glowMap[$glow]??'1').';';
$x.='}';wp_add_inline_style('nbu-terminal',$x);}add_action('wp_enqueue_scripts','nbu_t_vars',20);